### PR TITLE
Module uses Terraform AWS resources to notify SNS topic.

### PR DESCRIPTION
**Pull request by Jamie-BitFlight**
**What:**
- A small module that allows Terraform to cause an SNS notification via CloudWatch Events.

**Why:**
- Allows for tasks that are triggered by SNS to be triggered as part of the Terraform apply.

### CODE REVIEW

**Comment by Jamie-BitFlight** [comment]
Shall we update name to terraform-aws-cloudwatch-sns-topic-notify?

**Comment by Jamie-BitFlight** [comment]
@osterman i've updated this, and i didn;t realise I needed to address these. sorry for the 1 year wait.
It now likely needs additional changes such as the readme yaml and such.

**Comment by jamengual** [comment]
@Jamie-BitFlight is this still relevant?

**Comment by Jamie-BitFlight** [comment]
Haha. I think so. It did the job at the time. 

Can somebody review it for tf11 and I can make a tf12 version update.

**Comment by jamengual** [comment]
@Jamie-BitFlight we do not really support tf.11 any more so it will have to be a tf.12 version

**Comment by osterman** [comment]
Ok - we might end up abandoning it for the time being then.

**Comment by Jamie-BitFlight** [comment]
The goal of this was to trigger some lambda function originally. But since it is sns this allows any terraform project to do notifications as part of its run. 

When doing builds asynchronously for example this allows a callback to show completion.

I like the concept. But if it needs to be closed - give it a close. :)

**Pull request closed without merging**
